### ISSUE TITLE
Crash immediately after CrashHandler's automatic restart

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#28]
When I crash the app by starting an Audio Recording and then swiping the app closed from the task switcher, the app appears to restart after a few seconds, and then crash with the following stack trace:

```
05-02 12:35:17.912 7469-7499/org.beiwe.app E/art: No implementation found for long com.android.tools.profiler.support.network.HttpTracker$Connection.nextId() (tried Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId and Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId__)
05-02 12:35:17.912 7469-7499/org.beiwe.app E/AndroidRuntime: FATAL EXCEPTION: uploader_thread
                                                             Process: org.beiwe.app, PID: 7469
                                                             java.lang.UnsatisfiedLinkError: No implementation found for long com.android.tools.profiler.support.network.HttpTracker$Connection.nextId() (tried Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId and Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId__)
                                                                 at com.android.tools.profiler.support.network.HttpTracker$Connection.nextId(Native Method)
                                                                 at com.android.tools.profiler.support.network.HttpTracker$Connection.<init>(HttpTracker.java:191)
                                                                 at com.android.tools.profiler.support.network.HttpTracker$Connection.<init>(HttpTracker.java:186)
                                                                 at com.android.tools.profiler.support.network.HttpTracker.trackConnection(HttpTracker.java:280)
                                                                 at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.<init>(TrackedHttpURLConnection.java:49)
                                                                 at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.<init>(HttpsURLConnection$.java:50)
                                                                 at com.android.tools.profiler.support.network.httpurl.HttpURLWrapper.wrapURLConnectionHelper(HttpURLWrapper.java:40)
                                                                 at com.android.tools.profiler.support.network.httpurl.HttpURLWrapper.wrapURLConnection(HttpURLWrapper.java:55)
                                                                 at org.beiwe.app.networking.PostRequest.minimalHTTP(PostRequest.java:109)
                                                                 at org.beiwe.app.networking.PostRequest.doFileUpload(PostRequest.java:215)
                                                                 at org.beiwe.app.networking.PostRequest.doUploadAllFiles(PostRequest.java:287)
                                                                 at org.beiwe.app.networking.PostRequest.access$000(PostRequest.java:35)
                                                                 at org.beiwe.app.networking.PostRequest$1.run(PostRequest.java:266)
                                                                 at java.lang.Thread.run(Thread.java:762)
```

I think this crash (with the above stack trace) isn't caught by the CrashHandler, because the operating system pops up an alert message saying "Beiwe has stopped".

**Comment by zagorsky** [comment]
Appears to be fixed; may only have been caused by me using the Android Profiler.  This issue hasn't come up again.
