### ISSUE TITLE
Occasional registration crash: RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#30]
https://sentry.io/onnela-lab/android-development/issues/541076665/

Full stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at org.beiwe.app.storage.EncryptionEngine.unsafeHash(EncryptionEngine.java:61)
    at org.beiwe.app.storage.EncryptionEngine.safeHash(EncryptionEngine.java:44)
    at org.beiwe.app.DeviceInfo.getBluetoothMAC(DeviceInfo.java:105)
    at org.beiwe.app.ui.registration.RegisterActivity$1.doInBackground(RegisterActivity.java:125)
    at org.beiwe.app.ui.registration.RegisterActivity$1.doInBackground(RegisterActivity.java:122)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:353)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by zagorsky** [comment]
Eli should have fixed this in 0b0627d and ea5fcca, app version 2.3.3.
