### ISSUE TITLE
SmsReceivedLogger "before calling TextFileManager.start()"

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#36]
On my phone, this happened twice, most recently on March 9th.  I got the stack trace from Google Play (this is not on Sentry):

```
java.lang.RuntimeException: Unable to start receiver org.beiwe.app.listeners.SmsReceivedLogger: java.lang.NullPointerException: Tried to access textsLog before calling TextFileManager.start().
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3316)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.NullPointerException: Tried to access textsLog before calling TextFileManager.start().
	at org.beiwe.app.storage.TextFileManager.throwGetterError(TextFileManager.java:67)
	at org.beiwe.app.storage.TextFileManager.checkAvailableWithTimeout(TextFileManager.java:109)
	at org.beiwe.app.storage.TextFileManager.getTextsLogFile(TextFileManager.java:77)
	at org.beiwe.app.listeners.SmsReceivedLogger.handleIncomingMMS(SmsReceivedLogger.java:60)
	at org.beiwe.app.listeners.SmsReceivedLogger.onReceive(SmsReceivedLogger.java:35)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3309)
	... 8 more
```

We fixed this error so that it almost never happened; I think we succeeded at reducing the incidence of this error by about 99%.  Could you please try to figure out how it's possible for this to still happen, and whether there's a reasonable fix for it?

**Comment by biblicabeebli** [comment]
I'm taking a look at this, it is a ~multithreading issue where the app needs to wait until the text file writing is set up.

There is some locking/blocking going on, but I'm not sure it has ever done _exactly_ what we wanted.  It still _helps_ because the execution thread is instantiating on a separate execution thread, but it isn't actually locking.

This was probably introduced by the sms notification starting the background service if it isn't running, causing a race condition.  The default 75 millisecond wait is probably not enough, but this pattern should be improved.

**Comment by zagorsky** [comment]
This bug is super rare and should be even rarer now that the BackgroundService is running during a higher portion of the time.  It's a concurrency issue with no easy fix.  I'm closing the issue; we can reopen it if it appears again.
