### ISSUE TITLE
NPE on upload files before registration

### ISSUE THREAD

**Issue by sesterki** [onnela-lab/beiwe-android#40]
Here is the sentry error: https://sentry.io/onnela-lab/android-release/issues/559946034/

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at org.beiwe.app.storage.EncryptionEngine.unsafeHash(EncryptionEngine.java:61)
    at org.beiwe.app.storage.EncryptionEngine.safeHash(EncryptionEngine.java:44)
    at org.beiwe.app.DeviceInfo.getAndroidID(DeviceInfo.java:105)
    at org.beiwe.app.networking.PostRequest.securityParameters(PostRequest.java:324)
    at org.beiwe.app.networking.PostRequest.doFileUpload(PostRequest.java:220)
    at org.beiwe.app.networking.PostRequest.doUploadAllFiles(PostRequest.java:293)
    at org.beiwe.app.networking.PostRequest.access$000(PostRequest.java:35)
    at org.beiwe.app.networking.PostRequest$2.run(PostRequest.java:267)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by sesterki** [comment]
Fixed in ad4540292afde051833862ebb14830aecd46d2f2
